name: engine_pr_test
description: Graphs how many PRs in flutter/engine has tests

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  graphql: ^3.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  pedantic: ^1.9.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
