name: engine_pr_test
description: Graphs how many PRs in flutter/engine has tests

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  graphql: ^3.0.0
  json_annotation: ^3.0.1
  flutter:
    sdk: flutter

dev_dependencies:
  pedantic: ^1.9.0
  build_runner: ^1.8.1
  json_serializable: ^3.3.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - data/pr_data.json
